### ISSUE TITLE
Help with testing of version 0.3.0

### ISSUE THREAD

**Issue by KELiON** [KELiON/cerebro#339]
Hello, Cerebro users!

I've just released version [0.3.0-alpha](https://github.com/KELiON/cerebro/releases/tag/v0.3.0-alpha). It is well tested on Mac, but I would like to better test it on Linux and Windows before public release. So, I'd appreciate if you can help with tests! /cc @maximbaz @Stanzilla @BrainMaestro @SkaceKamen @codingmatty @AlexAlabyev and anyone else who want to do it:)

**Comment by maximbaz** [comment]
Installed, looking pretty good! Default plugins were installed on the first run, and I was able to uninstall some of them (🎉) and install other plugins. So far everything seems all right, I'll post if I discover something.

I see that [the list of default plugins](https://github.com/KELiON/cerebro/blob/f33bce8fc1e4ae23759dacaa4a537c963af97eb0/app/plugins/core/plugins/initializeAsync.js#L7-L14) doesn't contain yandex translator and google maps. Just wanted to confirm with you, was that a conscious decision to not include them? I don't need them personally, but I wonder if some people will find it confusing that these plugins got lost after upgrade to v0.3.0.

**Comment by SkaceKamen** [comment]
There's issue with basic-apps plugin on windows, at least for me. I'll try to investigate what is it.

**Comment by gepd** [comment]
Same as @SkaceKamen 

When I write any word related with a software installed in my machine, it doesn't show anything. I've tried uninstalling/installing the `Basic Apps` plugin, but I got same results.

**Comment by anishmworld** [comment]
The developer tools has this to say about `cerebro-basic-apps`. Maybe this is the root of the problem. Just guessing
``` 
Warning: C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js
Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
e @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
r @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
get @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
module.exports.Object.defineProperty.value @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
t @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
(anonymous) @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
t @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
module.exports.Object.defineProperty.value @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
t @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
(anonymous) @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
(anonymous) @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:1
(anonymous) @ C:\Users\anish\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-basic-apps\dist\index.js:2
Module._compile @ module.js:571
Module._extensions..js @ module.js:580
Module.load @ module.js:488
tryModuleLoad @ module.js:447
Module._load @ module.js:439
Module.require @ module.js:498
require @ internal/module.js:20
f @ main.bundle.js:1
setTimeout @ main.bundle.js:1
```

**Comment by KELiON** [comment]
Interesting, that it works in the same Cerebro version on mac:) @maximbaz can you confirm that it works on Linux and we have this problem only on Windows?

**Comment by BrainMaestro** [comment]
I get that error on the mac too for cerebro-open-web. It's actually just a warning for a deprecated feature. It does not affect the plugin at all. 

Anyway, I tested the new version on a mac and it looks great so far. 👍 I'll try doing the same on Windows when I get a chance.

P.S. Now that there's npm 5 that is just as fast as yarn, any plans on moving back?

**Comment by KELiON** [comment]
Probably I found a root cause of the issue (and yes, it was only windows-related), so I hope it works now with cerebro-basic-apps@1.0.7. Can you try to update the plugin and check again, please? /cc @anishmworld @gepd @SkaceKamen

**Comment by maximbaz** [comment]
I confirm, everything works fine on Linux. 

-----

Interesting though, while I was testing right now the basic-apps v1.0.7 was released and Cerebro updated it... and after update, basic apps stopped working until full Cerebro restart. 

It was like this, I have Chrome installed and I was typing "Ch" (and I saw Chrome in the results), then I typed "r" (in meanwhile probably plugin was updated) and Chrome disappears from results, and then whatever I typed (back to "Ch" or even "C") Chrome and any other app did not show up in the list anymore.

Might want to look in how Cerebro handles upgrades of cerebro-basic-apps.

**Comment by gepd** [comment]
Working here too!

I can also confirm that issue https://github.com/KELiON/cerebro/issues/301 is fixed

Each time I hide the search bar with the hotkey this windows error is displayed

![cerebro_error](https://user-images.githubusercontent.com/7091609/26923547-63087cc8-4c10-11e7-865e-94ecb901c937.png)

**Comment by anishmworld** [comment]
yep. It's working now.

**Comment by KELiON** [comment]
@gepd ok, thanks! Found the reason – it [works only on macos](https://github.com/electron/electron/blob/master/docs/api/app.md#apphide-macos), going to fix it

**Comment by codingmatty** [comment]
I really like that the last focused app will come back into focus, but it doesn't seem to work when I use `clipboard.writeText(...)` from electron's clipboard utility.
Is there something I need to do on the plugin's end to make it work, because that could make the clipboard plugin 100x better?

**Comment by KELiON** [comment]
@codingmatty good catch, looks like it is problem in core logic. So, we use `app.hide()` only in one place, but should use it everywhere instead of just `window.hide()`

**Comment by KELiON** [comment]
@codingmatty fixed it [here](https://github.com/KELiON/cerebro/pull/342), works perfect with clipboard plugin!

**Comment by maximbaz** [comment]
@KELiON I'm curious what exactly is the reason for not returning the focus? `window.hide()` is hiding one window, `app.hide()` hides all windows, so... is the second background BrowserWindow taking over the focus on macOS? (I don't have this issue on Linux btw). Will #340 fix this issue without having to add `app.hide()` everywhere? I guess you can manually kill the second renderer process and see if focus is not being stolen anymore.

**Comment by KELiON** [comment]
@maximbaz it is only Mac issue because of OS flow of managing windows and applications. I'm not sure, but looks like `BrowserWindow.hide()` works like minimize icon, and `app.hide()` works like <kbd>cmd+h</kbd>, so in first case focus is lost somewhere, when in the second case it returned back to the previous application

**Comment by JScharloo** [comment]
@KELiON im getting the same issue as @gepd. On a Debian-deriven distro. Deb 0.3.0.

`Uncaught Exception:
TypeError: _electron.app.hide is not a function
    at module.exports.exports.default.appWindow (/opt/Cerebro/resources/app.asar/main.js:473:19)
    at Function.toggleMainWindow (/opt/Cerebro/resources/app.asar/main.js:725:61)`

**Comment by KELiON** [comment]
@JScharloo it is already fixed in [0.3.0-alpha.2](https://github.com/KELiON/cerebro/releases/tag/v0.3.0-alpha.2)

**Comment by gepd** [comment]
@KELiON I'm still getting the error when I press the hotkey, however it does not happen when I press the esc key

**Comment by Stanzilla** [comment]
It errors when you press the keybind while the UI is already open https://i.imgur.com/xT1gIXa.png

**Comment by KELiON** [comment]
Released [version 0.3.0](https://github.com/KELiON/cerebro/releases/tag/v0.3.0)
